### ISSUE TITLE
Module doesn't work with the dynamic token rings enabled.

### ISSUE THREAD

**Issue by fishrobe** [reyzor1991/foundry-vtt-pf2e-flip-token#3]
There might be nothing you can do about this, but the tokens don't flip when the dynamic ring is enabled. At the moment I can turn the ring off, flip through the selected alternate images, and then go back to the orignal by turning the ring back on, which works ok, but f there is a way to make it work more naturally with the rings that would be great.

**Comment by reyzor1991** [comment]
It's works for me, with such settings, could you show your setting to I try to reproduce

<img width="474" alt="image" src="https://github.com/user-attachments/assets/7a2367f7-f946-4857-b8cb-0e7d40a0f4ad">

https://github.com/user-attachments/assets/7ec17a58-b584-4124-8b0d-ae2fc1484d96
